### ISSUE TITLE
new_orleans_pd_pprr

### ISSUE THREAD

**Issue by ayyubibrahimi** [ppact/processing#102]
I noticed that the script `new_orleans_pd_pprr.py` in clean is no longer being used because we decided to use the roster from IPM. Should this be deleted?

FYI - I started to add the `new_orleans_pd_commendations_2016_2021.csv ` but in the end I decided to create the new script, `new_orleans_pd_award.py`

**Comment by pckhoi** [comment]
I think it is fine to remove it.
