### ISSUE TITLE
IPM - New Orleans Sheriff's Office - Bookings and Charges (2015 - 2021) 

### ISSUE THREAD

**Issue by ayyubibrahimi** [ppact/processing#106]

**Comment by ayyubibrahimi** [comment]
@pckhoi I don't understand 80% of the data. I think that its useful for data on demographics and bond amounts but beyond that I don't see much utility until we get clarification on the codes used, if ever. Do you recommend dropping the columns until then?

**Comment by pckhoi** [comment]
Yes, there's no point in adding data that we don't understand.
