### ISSUE TITLE
Importation of duplicate department profiles into LLEAD 

### ISSUE THREAD

**Issue by ayyubibrahimi** [ppact/processing#156]
Below are duplicate department profiles that have been imported into the Django interface. For example, unique events are attached to both “Tangipahoa Parish Sheriff” and “Tangipahoa Sheriff’s Office”. These departments should be consolidated into one department named, for example, “Tangipahoa Parish Sheriff’s Office”. Let me know if you want to discuss further.

**Tangipahoa Parish Sheriff (and Tangipahoa Sheriff’s Office)**
**Lafayette Parish Sheriff’s (and Lafayette Sheriff)**

Rajiv hinted that these duplicates may be caused by how department profiles are created through importation from WRGL into the Django interface for llead.co

**Comment by pckhoi** [comment]
@rajivsinclair I believe this is an issue with the LLEAD backend and should be addressed there rather than within this repo. Data for Tangipahoa SO and Lafayette SO are certainly not duplicated here. Am I understanding correctly @ayyubibrahimi ?

**Comment by rajivsinclair** [comment]
This is actually an issue with the inconsistency between the dept name being displayed on LLEAD and the dept name that is imported with the data from this pipeline. In order to address this, I think we need to use a consistent unique slug to use as a unique identifier on both ends.

**Comment by pckhoi** [comment]
Not sure what you mean by dept name. Are you referring to `agency` field? In the [com-tangipahoa-so](https://www.wrgl.co/@ipno/r/com-tangipahoa-so/d7fddf65cf74f2cf389da932d6e2d172#preview), it is "Tangipahoa SO". How is it not consistent with the LLEAD backend?
