### ISSUE TITLE
rename `complaint` table to `allegation` and `complaint_uid` to `allegation_uid`

### ISSUE THREAD

**Issue by pckhoi** [ppact/processing#165]
@rajivsinclair the repository name is `complaint`. There's no repository rename functionality yet for wrgl so this could potentially mean losing all history. Renaming the primary key (complaint_uid -> allegation_uid) is less severe but will still make the commits after that non-comparable to the previous commits. The current names are a bit confusing but they are still semantically correct. Is it worth it?

**Comment by rajivsinclair** [comment]
I feel that losing history up til now for this table on WRGL is acceptable.

**Comment by ayyubibrahimi** [comment]
@pckhoi - did you also intend to rename the `charges` column for each cprr.py file to `allegation` or should I go ahead and make those changes?

**Comment by pckhoi** [comment]
Yes, please. That would be a great help. Before that though, https://github.com/ppact/processing/pull/164 needs to be merged. Could you resolve the conflicts there too? Just move stop and search columns into datavalid.yml.

**Comment by ayyubibrahimi** [comment]
Great. I'll handle the renaming. Conflicts have just been resolved.

**Comment by pckhoi** [comment]
Could you push the resolved commit so that I can review it?

**Comment by ayyubibrahimi** [comment]
I believe that I did. Can you see?

**Comment by pckhoi** [comment]
Sorry for not being clear. You need to make the changes directly to the branch `enhancement/consolidate-columns-info`:
- Add the stop and search columns to datavalid.yml
- Modify `rearrange_stop_and_search_columns` to use `datavalid_config`
- `make` the stop and search CSVs, ensure that everything runs perfectly.
I'm expecting a new commit under this PR: https://github.com/ppact/processing/pull/164

**Comment by ayyubibrahimi** [comment]
Got it. I've just pushed a new commit to PR: #164

**Comment by pckhoi** [comment]
Nice!

**Comment by ayyubibrahimi** [comment]
@pckhoi - Am I good to close?

**Comment by pckhoi** [comment]
Indeed!
