### ISSUE TITLE
trouble extracting tables

### ISSUE THREAD

**Issue by maheenakbarkhan** [ppact/processing#199]
@pckhoi 
Hi Khoi! Thanks so much for offering to help me out with the table extraction step. I followed the previous steps to train a custom model and am trying to run the "extract_tables_from_doc.py" script. This is the full command I run: 
` extract_tables_from_doc.py /Users/maheenkhan/Documents/InvisibleInstitute/ChampaignUseOfForce/UOFFullDetails.pdf /Users/maheenkhan/Documents/InvisibleInstitute/ChampaignUseOfForce/ChampaignTables --model-id e3c734f9-fa64-4467-b302-dcd2f3f7ced8 --batch-size 1`

And this is the error I receive when I do so:
```
Traceback (most recent call last):
  File "/Users/maheenkhan/Documents/InvisibleInstitute/processing/scripts/extract_tables_from_doc.py", line 197, in <module>
    fr_endpoint = os.environ['FORM_RECOGNIZER_ENDPOINT']
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'FORM_RECOGNIZER_ENDPOINT'
```

I cloned the processing repository and created a .env file with the environment variables, including FORM_RECOGNIZER_ENDPOINT, so I am unsure where the error is coming from. Thanks!!

**Comment by pckhoi** [comment]
It looks like this issue right here: https://stackoverflow.com/a/65854241/390370

I have made the fix in branch `bug/extract-tables-script`. Can you run the script again in that branch and let me know if it works?

**Comment by maheenakbarkhan** [comment]
Thanks, Khoi! That helped me get past the environment variable problem. Now, however, I'm getting a separate issue. This is the full command I am running for clarity (I was getting problems with the previous doc url I was using and I added the ---end-page argument);
`extract_tables_from_doc.py https://www.dropbox.com/s/nk77z0z6lzqkn5f/FrptOffFullDetails%20080116%20-%20080121%20%281%29_RD.pdf\?dl=0 /Users/maheenkhan/Documents/InvisibleInstitute/ChampaignUseOfForce/ChampaignTables --model-id e3c734f9-fa64-4467-b302-dcd2f3f7ced8 --batch-size 1 --end-page 728`

From this, I am getting the following error: 
```
Traceback (most recent call last):
  File "/Users/maheenkhan/Documents/InvisibleInstitute/processing/scripts/extract_tables_from_doc.py", line 243, in <module>
    reader = PDFBatchReader(args.build_dir, args.doc_url, args.batch_size, args.end_page)
  File "/Users/maheenkhan/Documents/InvisibleInstitute/processing/scripts/extract_tables_from_doc.py", line 47, in __init__
    with open(self.batch_dir / 'pageCount', 'r') as cf:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/maheenkhan/Documents/InvisibleInstitute/processing/scripts/build/pdf_batch_reader/batches/frptofffulldetails_080116_-_080121_(1)_rd.pdf/pageCount'
```

The following path does exist: 
`/Users/maheenkhan/Documents/InvisibleInstitute/processing/scripts/build/pdf_batch_reader/batches/frptofffulldetails_080116_-_080121_(1)_rd.pdf/`
but I'm not sure what pageCount is and when it should be created/what it should be. Thanks!

**Comment by maheenakbarkhan** [comment]
Thanks, Khoi! That helped me get past the environment variable problem. Now, however, I'm getting a separate issue. This is the full command I am running for clarity (I was getting problems with the previous doc url I was using and I added the ---end-page argument);
extract_tables_from_doc.py <link to document> /Users/maheenkhan/Documents/InvisibleInstitute/ChampaignUseOfForce/ChampaignTables --model-id e3c734f9-fa64-4467-b302-dcd2f3f7ced8 --batch-size 1 --end-page 728

From this, I am getting the following error:

Traceback (most recent call last):
  File "/Users/maheenkhan/Documents/InvisibleInstitute/processing/scripts/extract_tables_from_doc.py", line 243, in <module>
    reader = PDFBatchReader(args.build_dir, args.doc_url, args.batch_size, args.end_page)
  File "/Users/maheenkhan/Documents/InvisibleInstitute/processing/scripts/extract_tables_from_doc.py", line 47, in __init__
    with open(self.batch_dir / 'pageCount', 'r') as cf:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/maheenkhan/Documents/InvisibleInstitute/processing/scripts/build/pdf_batch_reader/batches/frptofffulldetails_080116_-_080121_(1)_rd.pdf/pageCount'
The following path does exist:
/Users/maheenkhan/Documents/InvisibleInstitute/processing/scripts/build/pdf_batch_reader/batches/frptofffulldetails_080116_-_080121_(1)_rd.pdf/
but I'm not sure what pageCount is and when it should be created/what it should be. Thanks!

**Comment by pckhoi** [comment]
Can you show me the full command this time? The first argument should be an HTTP link to the pdf, if it is a local file then I will have to make adjustments to the script. The normal flow is like this:

- Download the pdf from the HTTP URL to `build/pdf_batch_reader/docs/{filename}`
- Split the PDF into batches and store them into `build/pdf_batch_reader/batches/{filename}/{batch_number}.pdf`. During this process `build/pdf_batch_reader/batches/{filename}/pageCount` is created as a text file that simply contains the total page count in the PDF.
- Upload individual batch to FR and get back the results then concatenate them.

So it seems like you were using the path to a local file as the first argument. Can you confirm?

**Comment by maheenakbarkhan** [comment]
I actually changed the first argument to be a link to the pdf on dropbox so it isn't to a local file anymore!
