### ISSUE TITLE
Test alternatives to current matching

### ISSUE THREAD

**Issue by ahuds001** [ppact/processing#2]
Can we improve our current matching through using more fields than just first and last name in the datasets where they are available? For context, here is some research on probabilistic record linkage: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5065730/ 
There is a probabilistic record linkage package in python:
https://github.com/J535D165/recordlinkage

Separately flagging a string matching library that may also be useful in the future:
https://github.com/seatgeek/fuzzywuzzy

**Comment by pckhoi** [comment]
Thanks, I will take a look at all of them when I have more time.

We do match other fields such as "rank" and "hire_date" when they are available. But generally they are not very reliable.

**Comment by pckhoi** [comment]
@ahuds001 I have read this literature before and while probabilisitic classification might be something useful in the future we don't have training dataset for any of our data to figure out the weight. Once we do, adding a `ProbabilisticMatcher` class will probably be simple enough.

Regarding fuzzy string matching, our `StringSimilarity` class use Levenshtein distance and we even have `JaroWinklerSimilarity` class which give extra weight to common prefix and so work even better for names.

Note that the matching package is now migrated to https://github.com/pckhoi/datamatch
