### ISSUE TITLE
appeals

### ISSUE THREAD

**Issue by ayyubibrahimi** [ppact/processing#222]
@pckhoi - Q

Do you think that data from `appeal_hearings` should have their own repo on WRGL, like `use_of_force`, `stop_and_search`, `allegation`, `event`, and `personnel`? 

For now, we only have only received `appeal_hearing` data as tables/logs from NOPD, Baton Rouge PD, and Louisiana State PD. All of which are included in the events table. 

The question struck me now, because what I've currently extracted from Spacy is similar to what Tarak will produce from meeting minute pdfs, as the work that he has produced now in the documents [repo](https://hub.wrgl.co/@ipno/r/documents/refs/heads/main#filter) are `appeal_hearing` events extracted from the irrelevant noise that is otherwise contained within a minute meeting pdf. 

While the documents repo that Tarak has produced is currently used primarily to link documents to an officer, I imagine in the future that it would be useful to build on that repo to produce `appeal_hearing` logs for each agency, similar to those that we have received from NOPD, Baton Rouge PD, and Louisiana State PD. 

This question, for the time, is not time-sensitive as we've only received appeal_hearing transcripts from NOPD (because they don't have any appeal_hearing data within their meeting minutes, instead they release a transcript per hearing). Additionally, the data currently extracted is largely redundant (minus the ability to now link the document to the officer's timeline) from what is already in the '`clean/lprr_new_orleans_csc_2000_2016.csv`' as I've yet to extract the `incident_summary` from these transcripts, i.e., the description of why a given officer was `suspended `as noted in the `clean/lprr_new_orleans_csc_2000_2016.csv`'.  

Edit: It's not completely redundant. For example, In the '`clean/lprr_new_orleans_csc_2000_2016.csv`', a value that I just found in the column called `action_appealed`, which just states `suspended`, could be conjoined with corresponding a value in the `allegation` column from the Spacy table. An example that I've just come across is: "violated nopd rule by driving while intoxicated a crime that the district attorney chose not to prosecute appellant also suggests that the discipline imposed by nopd wa not commensurate with her alleged misconduct".  Common column being `docket_number`. Whereas, we know, in the allegations table for NOPD the extent of the allegation is usually limited to, for example: `rule 3; paragraph 4 - courtesy. `

However, as Tarak's model improves, and we're able to produce datasets both similar, and of higher quality, to what I've extracted from NOPD's appeal hearing transcripts  (attached) [new_orleans_csc_appeal_hearings_2012_2021.csv](https://github.com/ppact/processing/files/7787537/new_orleans_csc_appeal_hearings_2012_2021.csv), I wanted your opinion on whether creating a repo dedicating solely to appeal_hearing data makes sense.

**Comment by pckhoi** [comment]
Sure, it seems quite obvious that we should have an appeal hearing table. I remember we did have it as a separate table at some points but then forgot about it. Probably because it's not used yet on the LLEAD website.

**Comment by ayyubibrahimi** [comment]
Awesome

**Comment by ayyubibrahimi** [comment]
I'll hold off on consolidating the current `appeal_hearing `tables w fusion until POST has been integrated.
