### ISSUE TITLE
README link to wrgl broken

### ISSUE THREAD

**Issue by stefanv** [ppact/processing#231]
I'm trying to figure out what wrgl is, and Google is not helping much!

**Comment by pckhoi** [comment]
Thank you for the report, we will fix ASAP. Here's the link to wrgl: https://www.wrgl.co.

Full disclosure: I'm the creator of Wrgl and obviously we need to work on SEO more. But basically, Wrgl is like Git but for data, CSV in particular. You can keep your data in a Wrgl repository on your local computer, or you can host a wrgl repository with wrgld and provide access to others, or you can push to wrglhub which is even easier. You can see IPNO's public data here: https://hub.wrgl.co/@ipno

**Comment by stefanv** [comment]
Thanks @pckhoi! Could you also point me to the relevant storage/transport schemas, and the code repo (for wrgld etc.)?

**Comment by pckhoi** [comment]
Here's the repo: https://github.com/wrgl/wrgl

Documentation: https://hub.wrgl.co/doc/guides/quickstart/

Storage and transport format is undocumented for now but it is very similar to Git with the key differences being:
- Only support HTTP transport
- Packfile format is only used to pack objects together during transport (push/pull)
- Wrgl uses BadgerDB as the storage backend.
- The commit object does not hold a tree but a single table which is a list of blocks, each block is 255 rows.

If you're willing to look at the code, `pkg/encoding` and `pkg/objects` is the place to look if you're interested in encoding details.

**Comment by pckhoi** [comment]
Yes, this only focuses on CSV. But in the future, we may add support for other tabular formats such as Avro. No, Wrgl doesn't work with images and arbitrary binaries. But it can do a lot with CSV that other techs can't do such as: showing diff at the cell level, automated data profiling, data profile diffing, etc. Basically, anything that works with and enhances tabular data will find Wrgl a greater fit.
