### ISSUE TITLE
POST officer history profiles

### ISSUE THREAD

**Issue by ayyubibrahimi** [ppact/processing#239]
Hey @pckhoi -

I'm re-rerouting our email conversation re: POST officer history profiles and the cross_agency script here to this issue.  

As you mentioned that you'll have a better idea of how these officer history profiles can be incorporated once you see an example of the data consolidated into a single table, I've produced an initial table based on the 93 officer history profiles that we currently 
have. 
[post_officer_history_profiles_extracted.csv](https://github.com/ppact/processing/files/7902194/post_officer_history_profiles_extracted.csv)

For your reference, here is an officer history profile: 
[Officer History Report - Jacqualyn Robinson.pdf](https://github.com/ppact/processing/files/7902191/Officer.History.Report.-.Jacqualyn.Robinson.pdf)

As you'll notice, the output isn't perfect, but it's nearly there. I have plenty of training data still available, and I'll have plenty more once we receive the 360 officer history profiles that were requested based on the initial output of the cross_agency match script. I spoke with POST today. I hope to receive them soon. In the mean time, I thought that it would be best to share this with you now so that you'll have an idea of what to expect in the near future.

**Comment by pckhoi** [comment]
Nice! The only unfortunate thing is that we don't have this level of data for the majority of the officers. For that reason, I can only see this taken as an input into the cross-agency match script and nowhere else in the pipeline.

An interesting thing I noticed is that Jacqualyn seems to be holding 3 jobs at once! Is this the norm? Because the cross-agency match script works on the assumption that an officer can only holds one job at one place at any given time.

**Comment by ayyubibrahimi** [comment]
It is very unfortunate. The approximate cost is $20,000 to receive all 63,000 records. It might be worth revisiting the discussion of that cost with the team. 

I wouldn't go so far as to say that it is a norm, however, it is not uncommon for an officer to work for more than one agency during a given time. In such an instance, it is most common for an officer to work full-time for one agency and part-time for another.

**Comment by pckhoi** [comment]
Cool, I guess we can leave that logic of the cross-agency match script as-is for now. We can discard the `NonOverlappingFilter` when we want it to match more officers.
