### ISSUE TITLE
No rule to make target 'data/raw/rayne_pd/rayne_pd_pprr_2010_2020.csv'

### ISSUE THREAD

**Issue by pckhoi** [ppact/processing#250]
@ayyubibrahimi there's no entry for `rayne_pd` in `raw_datasets.json`.

**Comment by ayyubibrahimi** [comment]
Thanks. I must have worked on this when I was traveling on an overnight bus without internet access which would allow me to download the CSV directly from Dropbox. I corrected this bug in the rayne_pd pull request #226

**Comment by ayyubibrahimi** [comment]
I just opened a new pull request for this so that the fix is on the rayne_pd_personnel branch. Please see #251
