### ISSUE TITLE
Set UID of unknown officers to empty string across all tables

### ISSUE THREAD

**Issue by pckhoi** [ppact/processing#255]
@ayyubibrahimi can you please implement this when you have the time?

**Comment by ayyubibrahimi** [comment]
We are currently dealing with two types of unknown officers: 1) rows in which there is no first name or last name for a given officer, 2) rows in which we have replaced a generic name, like `narcotics` or `file for records only`, with an empty string. 

For the moment, we are dropping the rows in which there is no first name or last name for a given officer. Therefore, only those tables which contain generic names still have their unknown officer rows. I have set the UID for these officers to an empty string. Should we continue with this method, or should all unknown officers be kept and treated the same as the officer rows with generic names?

**Comment by pckhoi** [comment]
I don't see any practical differences between the two types. Are the records linked to the first type somehow different? If not then let's give them all the same treatment.

**Comment by ayyubibrahimi** [comment]
Sounds good.
