### ISSUE TITLE
WRGL

### ISSUE THREAD

**Issue by ayyubibrahimi** [ppact/processing#257]
Hey @pckhoi 

I just received the following error in my attempt to push to WRGL: 

```
pushing event...
To https://hub.wrgl.co/api/users/ipno/repos/event
status 502: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by pckhoi** [comment]
Thank you! It does seem that the endpoints could be flaky at least. Have you retried this command multiple times? Did it run for a while and then fail or did it fail immediately? I'm still pulling the event table atm. The data seems to be rather huge lately.

**Comment by ayyubibrahimi** [comment]
I tried it twice. In both instances it ran for a while before I received this message.

**Comment by pckhoi** [comment]
Did it fail at the event table both times? So I've just pushed the event table (after remaking it from the `main` branch) and it went alright:
```
wrgl push event refs/heads/event:refs/heads/main
To https://hub.wrgl.co/api/users/ipno/repos/event
   0afedd2..4ff6679  event       -> main
```
I made the stupid mistake of upgrading the nodes before inspecting resource allocation. My guess is that there is a memory leak. Unfortunately, there's no artifact for me to inspect anymore. Please try pushing other branches and let me know if it happens again.

**Comment by ayyubibrahimi** [comment]
Sorry for the delay. I was traveling yesterday. I decided to start from the beginning by re-running `wrgl pull --all` and received the following message:

```
pulling event...
stream error: stream ID 143; PROTOCOL_ERROR; received from peer
```

**Comment by pckhoi** [comment]
Thank you! It seems that you're hitting a Go bug (see https://github.com/golang/go/issues/47635, https://github.com/golang/go/issues/42777) which was probably caused by making a lot of requests to the server on a single connection.

There's no easy way to fix it other than to wait for the bug fixes to land in a new Go release. That said, it should be fine if you simply reattempt the same command again because you will start with a fresh connection.

I'm going to scour the command for more bugs and let you know when I think it is more rock solid.

**Comment by ayyubibrahimi** [comment]
Awesome. I ran push again and it worked. Thanks!

**Comment by ayyubibrahimi** [comment]
All good! Thanks for guiding me through the bugs.

 I was feeling adventurous. 

The command finished running, but along the way I encountered these errors:
```
pulling per-madisonville-pd...
⠙ Fetching objects (0/-, 0 it/min) 
error: error fetching objects: error requesting upload pack: status 500: {"message":"Internal Server Error"}
pulling per-mandeville-pd...
⠼ Fetching objects (0/-, 0 it/min) 
error: error fetching objects: error requesting upload pack: error reading packfile version: EOF


pulling person...
⠋ Fetching objects (66/-, 38 it/min) 
error: error fetching objects: error requesting upload pack: status 400: {"message":"empty wants list"}
pulling personnel...
⠦ Fetching objects (0/-, 0 it/min) 
error: error fetching objects: error requesting upload pack: status 500: {"message":"Internal Server Error"}
pulling sas-new-orleans-pd...
⠴ Fetching objects (0/-, 0 it/min) 
error: error fetching objects: error requesting upload pack: status 500: {"message":"Internal Server Error"}
pulling stop-and-search...
⠦ Fetching objects (0/-, 0 it/min) 
error: error fetching objects: error requesting upload pack: status 500: {"message":"Internal Server Error"}
pulling uof-new-orleans-pd...
⠧ Fetching objects (0/-, 0 it/min) 
error: error fetching objects: error requesting upload pack: status 500: {"message":"Internal Server Error"}
```

**Comment by pckhoi** [comment]
Thank you! Wrglhub is experiencing a strange memory issue in its object storage. I'll let you know when the issue is fixed.

**Comment by pckhoi** [comment]
So there was no issue with `wrgl pull --all --depth 1`. After fixing the memory issue, I tried the command and there's no error.

**Comment by ayyubibrahimi** [comment]
Just re-ran the following commands and it worked without any issues. Thanks! 

```
rm -rf .wrgl/kv .wrgl/files
wrgl init
wrgl pull --all --depth 1

```

**Comment by ayyubibrahimi** [comment]
@pckhoi  - 

I'm receiving the following when for every branch when I run `wrgl pull --all`:
```

pulling use-of-force-officers...
error: error fetching refs: status 500: {"message":"Internal Server Error"}
```

**Comment by pckhoi** [comment]
@ayyubibrahimi Thank you for reporting! This error seems to have been caused by expired token. From now on it will print more accurate error message:
```
error: error fetching refs: status 401: {"message":"token is expired by 385h12m50s"}
```
Please login and try again:
```bash
wrgl credentials authenticate https://hub.wrgl.co/api
```

**Comment by ayyubibrahimi** [comment]
Awesome. I'll give it a go. Thanks!

**Comment by ayyubibrahimi** [comment]
It's working. Thanks Khoi!

**Comment by ayyubibrahimi** [comment]
Just ran wrgl pull --all, as you noted in the email. This is the error message I receive:

```
pulling allegation...
⠧ Fetching objects (0/-, 0 it/min) 
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x70f174]

goroutine 1 [running]:
github.com/wrgl/wrgl/pkg/encoding/packfile.(*PackfileReader).Close(0x0)
        /home/runner/work/wrgl/wrgl/pkg/encoding/packfile/packfile.go:163 +0x14
panic({0xb47aa0, 0x121f320})
        /opt/hostedtoolcache/go/1.17.7/x64/src/runtime/panic.go:1047 +0x266
github.com/wrgl/wrgl/pkg/encoding/packfile.(*PackfileReader).ReadObject(0x0)
        /home/runner/work/wrgl/wrgl/pkg/encoding/packfile/packfile.go:143 +0x20
github.com/wrgl/wrgl/pkg/api/utils.(*ObjectReceiver).Receive(0xc0060e8d20, 0xc006af7910, 0xc0060f8d00)
        /home/runner/work/wrgl/wrgl/pkg/api/utils/object_receiver.go:88 +0x3c
github.com/wrgl/wrgl/pkg/api/client.(*UploadPackSession).Start(0xc000464500, 0xc0e0b3)
        /home/runner/work/wrgl/wrgl/pkg/api/client/upload_pack_session.go:105 +0x1b8
github.com/wrgl/wrgl/cmd/wrgl/fetch.fetchObjects(0x0, {0xd22ec8, 0xc00046e228}, {0xd23448, 0xc00046a5d0}, 0xc0001dd7e0, {0xc0063e3000, 0x0, 0xc0000fe180}, 0x0)
        /home/runner/work/wrgl/wrgl/cmd/wrgl/fetch/root.go:370 +0x305
github.com/wrgl/wrgl/cmd/wrgl/fetch.Fetch(0xc0001dd958, {0xd22ec8, 0xc00046e228}, {0xd23448, 0xc00046a5d0}, 0x4e2994, {0xc0002f4fd0, 0x6}, {0xc000110580, 0x15d}, ...)
        /home/runner/work/wrgl/wrgl/cmd/wrgl/fetch/root.go:382 +0x266
github.com/wrgl/wrgl/cmd/wrgl.pullSingleRepo(0x3, 0xc0003d4f40, {0xd22ec8, 0xc00046e228}, {0xd23448, 0xc00046a5d0}, {0xc0001ddcc0, 0x8, 0x1}, 0x0, ...)
        /home/runner/work/wrgl/wrgl/cmd/wrgl/pull_cmd.go:209 +0x3bd
github.com/wrgl/wrgl/cmd/wrgl.pullCmd.func1(0xc000317400, {0xc0003266b0, 0x0, 0x1})
        /home/runner/work/wrgl/wrgl/cmd/wrgl/pull_cmd.go:110 +0xbb0
github.com/spf13/cobra.(*Command).execute(0xc000317400, {0xc0003266a0, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000302a00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        /home/runner/work/wrgl/wrgl/wrgl/main.go:16 +0x55
```

**Comment by pckhoi** [comment]
Thank you! What version of command line were you using? What does it say when you run `wrgl --version`?

Version 0.11.x change pull/push protocol but not necessarily storage format so just updating the command line should work.

**Comment by ayyubibrahimi** [comment]
Sorry. I didn't see the message and so I didn't update first. It's working now.
