### ISSUE TITLE
cross_agency

### ISSUE THREAD

**Issue by ayyubibrahimi** [ppact/processing#267]
Hey @pckhoi - I expect to have acquired all 450 POST officer history reports from the POST agency within the next 3 weeks, therefore, I wanted to re-visit the conversation about how we can best automate the process of cross-referencing POST officer history reports with the output of the cross_agency script. Below is an example of a POST officer history report, and the output from a spacy model when applied to POST testing data. 

[OHR - Ryan Washington.pdf](https://github.com/ppact/processing/files/8274854/OHR.-.Ryan.Washington.pdf)

[spacy_post_test.csv](https://github.com/ppact/processing/files/8274857/spacy_post_test.csv)

**Comment by pckhoi** [comment]
Perhaps we can create a `post-officer-history` table that references `uid` from `personnel`. Have the cross_agency script read that table and integrate that knowledge into the `person` table. I guess the `post-officer-history` table would act like the `constraint` table. The only difference is that it takes no direct edit. The script should also output matches that are in conflict with `post-officer-history` and matches that don't appear in `post-officer-history` to separate files.

**Comment by ayyubibrahimi** [comment]
@pckhoi I was thinking that it's probably a good time to re-produce the constraints table. I've identified about 100 or clusters who should be labeled with an attract_id while the remaining thousand clusters should not be considered the same person until we can cross-reference the data with post history reports. Did you want me to produce the constraints table in the same manner as the first, or did you have something else in mind?

**Comment by pckhoi** [comment]
Yes, please go ahead with that.
