### ISSUE TITLE
allegation table switched back to using `tracking_number` instead of `tracking_id`.

### ISSUE THREAD

**Issue by pckhoi** [ppact/processing#277]
https://hub.wrgl.co/@ipno/r/allegation/commits/a5948141cde83da6e565cdeab0b89ee7#changes

**Comment by ayyubibrahimi** [comment]
I don't think it ever changed to `tracking_id` as those changes are in pending #266

**Comment by pckhoi** [comment]
Looks like it did changed in [cf7952b42492456e3c2d713b98d06647](https://hub.wrgl.co/@ipno/r/allegation/commits/cf7952b42492456e3c2d713b98d06647#changes) which is the previous commit. Sorry for not reviewing #266 sooner. We should try to merge it soon.

**Comment by ayyubibrahimi** [comment]
This has been corrected. Closing.
