### ISSUE TITLE
`uid` column for the `use-of-force` table

### ISSUE THREAD

**Issue by huy-d-nguyen** [ppact/processing#287]
Hi @ayyubibrahimi cc @pckhoi , previously the `use-of-force` table have one column name `uid` to match that row with one specific officer but for now the column has been removed, can you help us to check and add that column again? Many thanks.

**Comment by ayyubibrahimi** [comment]
@huy-d-nguyen the 'use-of-force' table has been split into three tables: 'use-of-force', 'use-of-force-officers' and 'use-of-force-citizens'. The column named 'uid' exists only in the 'use-of-force-officers' table and all three tables can be joined on the column named 'uof_uid'. These changes have just been pushed.

**Comment by huy-d-nguyen** [comment]
Thank you, we will take a look on those tables.
