### ISSUE TITLE
Rows with the same primary key in uof officers and uof citizens

### ISSUE THREAD

**Issue by pckhoi** [ppact/processing#290]
[use-of-force-officers](https://hub.wrgl.co/@ipno/r/data/refs/heads/use-of-force-officers#filter) with `uid` = `023bf5a680011bf39478f42fc3a3a01a`.
[use-of-force-citizens](https://hub.wrgl.co/@ipno/r/data/refs/heads/use-of-force-citizens#filter) with `uof_citizen_uid` = `09066e8d8a8f146a59e7c3127ef2495a`. And `uof_uid` isn't include in `uof_citizen_uid` generation from right now, which I think is an error. There is no identification column for citizen (which is fine) so each should be further identified by not just their demographic but also `uof_uid`.

@ayyubibrahimi

**Comment by pckhoi** [comment]
And Wrgl shouldn't allow commit with the same primary key for multiple rows. I'm going to fix it soon. https://github.com/wrgl/wrgl/issues/2

**Comment by pckhoi** [comment]
@huy-d-nguyen

**Comment by ayyubibrahimi** [comment]
I've added `citizen_sex`, `citizen_race`, and `uof_uid` to the generation of `uof_citizen_uid` in pr #291
