### ISSUE TITLE
No uof_uid in any event records in Event table

### ISSUE THREAD

**Issue by huy-d-nguyen** [ppact/processing#298]
Hi @ayyubibrahimi, we do not see any `uof_uid` values in Event table. Please take a look on it.
Thanks

**Comment by pckhoi** [comment]
Looks like the column is there but it is mostly NA.

**Comment by ayyubibrahimi** [comment]
Likely a mistake by me. I will look into it now.

**Comment by ayyubibrahimi** [comment]
Figured out the issue. A pr to resolve this will be opened soon.

**Comment by ayyubibrahimi** [comment]
This issue is addressed in pr #299

**Comment by ayyubibrahimi** [comment]
@huy-d-nguyen - also please be aware that the `kind` name has changed in the Event table from `occur_date` to `uof_occur_date`
