### ISSUE TITLE
Exclude stop and search data

### ISSUE THREAD

**Issue by pckhoi** [ppact/processing#303]
Right now stop and search data takes up 80% of the entire event records, which total up to 1M+ records. It causes processing, committing and pushing data significantly slower. If we're not using stop and search data for any particular purpose right now then I propose keeping them off the main output tables e.g. `event` and `personnel`.

In the event that we are using those records then perhaps we should still keep them separate from other tables as they are not frequently updated but will cause significant strain whenever they land.

**Comment by pckhoi** [comment]
@rajivsinclair 
@ayyubibrahimi

**Comment by pckhoi** [comment]
For now I think we only need to modify these 2 lines from `fuse/new_orleans_pd.py`:
```
    personnel = fuse_personnel(pprr_ipm, lprr, pprr_csd, sas, uof_officers, brady)
    events_df = fuse_events(pprr_ipm, pprr_csd, cprr, uof, award, lprr, sas)
```

Just remove `sas` from both of them is enough I think.

**Comment by ayyubibrahimi** [comment]
This has been addressed. Closing.
