### ISSUE TITLE
analysis

### ISSUE THREAD

**Issue by ayyubibrahimi** [ppact/processing#305]
@pckhoi I was thinking about adding an analysis repo to store the notebooks in which I've analyzed some of the processed data. Thoughts?

**Comment by ayyubibrahimi** [comment]
Ofc. Atm, I plan to do a pretty superficial analysis of departments for which we have 5+ years of allegations data, i.e., # of allegations over time, allegation type over time, allegation distribution across officers in the dept, etc. Anything you think I should be looking into?

**Comment by ayyubibrahimi** [comment]
In the beginning I think that the analysis will be surface level, but that in the future it may become more complex, i.e., when we further explore networks. 

Awesome. Sounds good. I'll work on integrating those stages.

**Comment by pckhoi** [comment]
Sounds good. Regarding analysis, either this repo or a new repo is fine to me.

**Comment by ayyubibrahimi** [comment]
This has been addressed.
