### ISSUE TITLE
Use of force uof_occur event problem

### ISSUE THREAD

**Issue by huy-d-nguyen** [ppact/processing#317]
Hi @ayyubibrahimi , cc @pckhoi .  We have one question related to the use of force `uof_occur` event. It looks like you have clean the field `uid` of those `uof_occur` events (empty value) due to the implementation of the use-of-force-officer relation. But should we clean the field agency too because many officer point to the same use of force still can be in different department too. Or should we create different event for different officer inside that table ? Because previously, we link the officer to department via event, if you left the `uid` field of the table `event` blank, we need to change our current implementation. How do you feel about that? Can we implement like the latter one (keep the uid, create multiple `uof_occur` events).

**Comment by pckhoi** [comment]
Are you saying that inside `use-of-force-officers`, there are rows that share the same `uof_uid` but different `agency`? Or point to officers from different agencies?

**Comment by huy-d-nguyen** [comment]
no, I mean currently inside the `event` table, we link the `uof_occur` event to one `use-of-force` via `uof_uid`, but that `use-of-force` could be link to many officers, and those could have different agency, but we still have `agency` value inside the `uof_occur` event, too. It makes us feel ambiguous.

**Comment by pckhoi** [comment]
There are no `use-of-force` row that could link to officers from multiple agencies. You can take agency from any table that has that field.

It's a little redundant to have the `agency` field in multiple places, sure. But I don't see how it is an issue yet.

**Comment by huy-d-nguyen** [comment]
Ok, got it. But up to now, we used the `event` table as the through table to link between the `department` and `officer`, but as the implementation of the n ew `use-of-force`, those `use-of-force` events no longer contain the `uid` inside them. So we need to link the `department` with the `officer` directly`. How do you think about that? Is the link between the department and officer stable for now? We need to ask that before updating the relation because changing the relation of department and officer will update a huge of code lines in our backend.

**Comment by pckhoi** [comment]
By "department", do you mean "agency"?

There are no `uid` that appears in more than one agency. I can guarantee that.
