### ISSUE TITLE
Second date info for appeal hearing

### ISSUE THREAD

**Issue by huy-d-nguyen** [ppact/processing#323]
Hi @ayyubibrahimi , previously we have the field `second-date` for the appeal hearing related event but it was removed. Can you help us to check and add that field again? In case that field cannot be added again, please let us know, thank you.

**Comment by ayyubibrahimi** [comment]
hey @huy-d-nguyen - Apologies for not keeping you in the loop. Rajiv, Sukari, and I, with the rest of the IPNO team, decided to drop the `second-date` in favor of highlighting the most final appeal hearing event/date. Does this still sound right to you? @rajivsinclair @lsukaristone

**Comment by rajivsinclair** [comment]
Yes, thanks for clarifying here @ayyubibrahimi. I forgot that we had reached this conclusion - sorry for the confusion @huy-d-nguyen

**Comment by huy-d-nguyen** [comment]
we got it, thank you all.
