### ISSUE TITLE
Tangipahoa SO 2015-2021

### ISSUE THREAD

**Issue by ayyubibrahimi** [ppact/processing#63]
Hey @pckhoi 

I'm getting the error below when I run make and I can't figure out a solution. Thoughts?

File "/mnt/c/Users/AyyubI/processing/match/tangipahoa_so.py", line 22, in deduplicate_cprr_officers
    matcher.save_clusters_to_excel(data_file_path(
AttributeError: 'ThresholdMatcher' object has no attribute 'save_clusters_to_excel'
make: *** [Makefile:193: data/match/cprr_tangipahoa_so_2015_2021.csv] Error 1

**Comment by pckhoi** [comment]
Looks like you haven't updated to latest version of datamatch. Try running `pip install -r requirements.txt` and try make again.

**Comment by ayyubibrahimi** [comment]
I have datamatch 0.1.8. Is there a more updated version?

**Comment by pckhoi** [comment]
There isn't a newer version. If it's already 0.1.8 then it should have the method `save_clusters_to_excel`. Maybe it's something to do with your environment?

**Comment by pckhoi** [comment]
We can start a session to look into this if you want.

**Comment by ayyubibrahimi** [comment]
Must be something with my environment. I'm going to spend more time on it. If I fail, do you want to meet your Saturday morning/my Friday night, or the next? Also free next week

**Comment by pckhoi** [comment]
Just shoot me an email the day before. I can join a session on most
mornings.

**Comment by ayyubibrahimi** [comment]
Awesome. Let's do tomorrow morning then.

**Comment by pckhoi** [comment]
Okay.

**Comment by ayyubibrahimi** [comment]
I figured it out. No need to meet. Thanks!

**Comment by pckhoi** [comment]
Nice!
