### ISSUE TITLE
New Orleans SO CPRR 2020

### ISSUE THREAD

**Issue by ayyubibrahimi** [ppact/processing#65]

**Comment by ayyubibrahimi** [comment]
@rajivsinclair @pckhoi @lsukaristone 

The action column in this dataset is mostly populated with dates for suspensions, resignations, and terminations. Should these become events?

**Comment by pckhoi** [comment]
No, we already have the `officer_left` event.  Recently I added the `left_reason` column to event table, you can set it to "resignation" or "termination". Regarding suspension date, are we interested in that?

**Comment by ayyubibrahimi** [comment]
Unless it complicates unreasonably, I am

**Comment by pckhoi** [comment]
Sure, let's add in the suspension event, you will probably want to link it to both the officer and the complaint via `uid` and `complaint_uid`.

**Comment by ayyubibrahimi** [comment]
Ok.

**Comment by ayyubibrahimi** [comment]
What do you think about arrest date? There are a few here as well.

**Comment by pckhoi** [comment]
Sure, why not? As long as it isn't a duplication.

**Comment by ayyubibrahimi** [comment]
A duplication in what way? Some individuals will be arrested on the same day that they are terminated. Should that be consolidated into termination?

**Comment by pckhoi** [comment]
Oh no, not saying the arrest event is a duplication at all. `left_reason` column: https://github.com/ppact/processing/blob/main/lib/columns.py#L182
