### ISSUE TITLE
Add flake8 check for all pull requests

### ISSUE THREAD

**Issue by pckhoi** [ppact/processing#7]
The linter for this repo is officially flake8. All pull requests must pass flake8 check before getting merged to `main` branch.

**Comment by pckhoi** [comment]
@ayyubibrahimi are you interested in adding this?

**Comment by ayyubibrahimi** [comment]
Thanks.

**Comment by pckhoi** [comment]
Also default max-line-length is 79. We want to increase this to 120.

**Comment by pckhoi** [comment]
@ayyubibrahimi I was thinking of take on this task myself. Why did you close this?

**Comment by ayyubibrahimi** [comment]
Misunderstanding, my bad. I treated it as a comment as opposed to a pull request.
