### ISSUE TITLE
Get rid of `data_production_year` column?

### ISSUE THREAD

**Issue by pckhoi** [ppact/processing#71]
This column appear in complaints, use-of-force and appeal table and generally have the year the original dataset was given to us. E.g. `2019` if the file name is `new_orleans_pd_use_of_force_2012-2019.csv`. I don't see this column serving any practical purpose and so I want to remove it. Any objection? @rajivsinclair @lsukaristone @ayyubibrahimi

**Comment by rajivsinclair** [comment]
Could it be replaced with a more precise `production_date` column instead? What if we need to see how current a particular record is or if we have two versions of the same record and we want to know which is more current?

**Comment by pckhoi** [comment]
To answer the first question, I guess we can glean the production date off of file timestamp on Dropbox. @ayyubibrahimi are there any method that can be more precise?

Regarding the second question I have never seen the same record given to us from the same agency under different dates before so the usefulness of this is in doubt. It is possible for the same record to arrive from different agencies on different dates but we usually just pick one agency over the other as there can be no interesting or new columns to be found in the other agency's data. We did that also to keep things simple.

Given that the usefulness of this is in doubt and generally not applicable to most agencies, my feeling is to discard this field because should the needs arise, we likely still need to do substantial exploration/experimentation to see what we can extract as it would be something we have never done before. Am I missing anything?

**Comment by ayyubibrahimi** [comment]
Taking the file timestamp from Dropbox sounds best.

**Comment by pckhoi** [comment]
What is the consensus in this? Again I'm all for removing this column because for now it doesn't really serve any purpose, it only give us a false sense safety when in reality nobody know how to utilize this column because even the scenario is really vague. If and when a record arrive on different dates, it still won't show up in the final data as 2 records but will likely be caught in the clean stage so this column is pointless.

**Comment by rajivsinclair** [comment]
Hi, sorry for not following up sooner. Yes, please go ahead and remove this column.
