### ISSUE TITLE
Lake Charles PD CPRR 2020

### ISSUE THREAD

**Issue by ayyubibrahimi** [ppact/processing#74]

**Comment by ayyubibrahimi** [comment]
@pckhoi  Hey Khoi, this dataset refuses to download after I add it to run_datasets.json and run make. Are you having the same issue?

**Comment by pckhoi** [comment]
No I haven't tried it. What's the output when you run `scripts/rawfiles.sh`?

**Comment by pckhoi** [comment]
I suspect that adding `make download_links` to line 14 of `scripts/rawfiles.sh` might make the problem go away. Can you confirm?

**Comment by ayyubibrahimi** [comment]
The output from `scripts/rawfiles.sh`: 

"usage: scripts/rawfiles.sh SUB_DIR

Prints raw files under SUB_DIR of build/raw folder.

positional arguments:
  SUB_DIR               sub-directory under build/raw folder. These folders are generated from raw_datasets.json therefore SUB_DIR must be one of the keys found in that file. " 

Adding` make download_links` to line 14 of `scripts/rawfiles.sh` had no effect.

**Comment by pckhoi** [comment]
What is the key in `raw_datasets.json` that you put the new file under? "lake_charles"?

**Comment by ayyubibrahimi** [comment]
Yes

**Comment by pckhoi** [comment]
Try this and see if it fixes it: `scripts/rawfiles.sh lake_charles_pd`

**Comment by ayyubibrahimi** [comment]
When I run `scripts/rawfiles.sh lake_charles_pd` I get the error: 

"curl: (22) The requested URL returned error: 404
link isn't working: https://www.dropbox.com/s/bjjptnrode22um2/lake_charles_pd_cprrr_2020.csv?dl=1
make: *** [raw_datasets.mk:12: data/raw/lake_charles_pd/lake_charles_pd_cprrr_2020.csv] Error 22"

Despite the fact that the Dropbox link is "https://www.dropbox.com/s/xzd2pr1nozb01ux/lake_charles_pd_cprr_2020.csv?dl=1" 

Earlier, I was curious as to if the Dropbox link was the issue, so I generated the new one above, yet the rawfiles.sh file seems to not recognize the new link. 

That said, when I change the key in` raw_datasets.json` to` lake_charles` and run `scripts/rawfiles.sh lake_charles` the new link is recognized and downloaded. The issue is therefore fixed, but only with the key as `lake_charles`

**Comment by ayyubibrahimi** [comment]
Another issue. The clean file isn't being generated when I run make.

**Comment by pckhoi** [comment]
Okay, what is the name the file that is not being generated? Also can you share the branch with me?

**Comment by ayyubibrahimi** [comment]
`clean/cprr_lake_charles_pd_2020.csv` isn't being generated.

**Comment by pckhoi** [comment]
https://github.com/ppact/processing/pull/77 should fix the issue. Makes sure to run `scripts/rawfiles.sh lake_charles_pd` and update your script with the correct path and everything should work.

**Comment by ayyubibrahimi** [comment]
Apologies for the late follow-up, but I've been out all week. 

When I change the key from `scripts/rawfiles.sh lake_charles` to `scripts/rawfiles.sh lake_charles_pd` I receive the following error: 

```
Traceback (most recent call last):
  File "/mnt/c/Users/ayyubi/processing/scripts/write_download_links.py", line 79, in <module>
    os.removedirs(subdir)
  File "/usr/lib/python3.9/os.py", line 243, in removedirs
    rmdir(name)
OSError: [Errno 39] Directory not empty: 'build/raw/lake_charles'
make: *** [raw_datasets.mk:8: download_links] Error 1
```

It does work when I clone a new repo, add and run `scripts/rawfiles.sh lake_charles_pd`

**Comment by pckhoi** [comment]
Hey, next time you just need to run `make clean` which removes the build folder. Then everything will be back to a clean slate.

**Comment by ayyubibrahimi** [comment]
Awesome.
