### ISSUE TITLE
LPRRs

### ISSUE THREAD

**Issue by ayyubibrahimi** [ppact/processing#89]
Hey @pckhoi 

Re `events`: what does the `appeal_render` event refer to? I wasn't sure if it referred to the "disposition" date, so I added `appeal_disposition` to the event table. (this event currently only applies to louisiana_state_csc.py).

Re `events`: what do you think about changing the prefix from "hearing" to "appeal_hearing" for the event `appeal_hearing ` (this currently only applies to baton_rouge_pd.py) because I imagine that we'll have other types of hearings.

**Comment by pckhoi** [comment]
Re `appeal_render`: the date came from a column named "rendered" in `raw/louisiana_state_csc/louisianastate_csc_lprr_1991-2020.csv`. It is probably the disposition date. What do you think? Which name should we keep?

Re `events`: yes, seems sensible to me.

**Comment by ayyubibrahimi** [comment]
I'll confirm with LSC that render date refers to disposition date. if so, I say we change it to disposition date.
