### ISSUE TITLE
Plaqumines Sheriff's Office - Personnel Records (2018)

### ISSUE THREAD

**Issue by ayyubibrahimi** [ppact/processing#93]

**Comment by pckhoi** [comment]
@ayyubibrahimi Holly Hardin Daniel Swear from Plaquemines SO CPRR 2019 is probably the same person as Holly Hardin from this dataset but flagged as different because the last name from PPRR is recorded as "Hardin" instead. Could you take a look at that?

**Comment by pckhoi** [comment]
Also found 2 officers with strange birth year:
```
                                        uid   last_name middle_name middle_initial first_name  birth_year  birth_month  birth_day race  sex
    411    04ee0c2b2eaf07d80a3f53341ca2149e  Duplessis          NaN              D    Gabriel      1049.0          NaN        NaN  NaN  NaN
    14551  af1ae486f61a4d9c259b652681c096b9    Lejeune          NaN              W     Walter      1040.0          NaN        NaN  NaN  NaN
```

**Comment by ayyubibrahimi** [comment]
Just received confirmation on the dates and fixed them.

Holly Hardin and Daniel Swear are two different people.
